//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMI.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessagesExceptions() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMI.Domain.Exceptions.MessagesExceptions", typeof(MessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un producto con el mismo nombre..
        /// </summary>
        public static string DuplicatedProductName {
            get {
                return ResourceManager.GetString("DuplicatedProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del producto solo puede contener letras, números y espacios..
        /// </summary>
        public static string InvalidCharactersProductName {
            get {
                return ResourceManager.GetString("InvalidCharactersProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio del producto debe ser mayor a 0..
        /// </summary>
        public static string InvalidProductPrice {
            get {
                return ResourceManager.GetString("InvalidProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El stock del producto no puede ser negativo..
        /// </summary>
        public static string InvalidProductStock {
            get {
                return ResourceManager.GetString("InvalidProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción del producto no puede tener más de 40 caracteres..
        /// </summary>
        public static string MaxLengthProductDescription {
            get {
                return ResourceManager.GetString("MaxLengthProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del producto no puede tener más de 20 caracteres..
        /// </summary>
        public static string MaxLengthProductName {
            get {
                return ResourceManager.GetString("MaxLengthProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a l precio del producto no puede ser mayor a 1,000,000..
        /// </summary>
        public static string MaxValueProductPrice {
            get {
                return ResourceManager.GetString("MaxValueProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El stock del producto no puede superar las 10,000 unidades..
        /// </summary>
        public static string MaxValueProductStock {
            get {
                return ResourceManager.GetString("MaxValueProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el producto.
        /// </summary>
        public static string NotExistProduct {
            get {
                return ResourceManager.GetString("NotExistProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del producto es obligatorio..
        /// </summary>
        public static string RequiredProductName {
            get {
                return ResourceManager.GetString("RequiredProductName", resourceCulture);
            }
        }
    }
}
